-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 10:34:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NOT NULL,
  `lastname_user` VARCHAR(45) NOT NULL,
  `nickname_user` VARCHAR(45) NOT NULL,
  `password_user` VARCHAR(300) NOT NULL,
  `type_user` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type_diets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type_diets` (
  `id_type` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `name_type` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_type`, `name_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`diets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`diets` (
  `id_diet` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(10,2) NOT NULL,
  `number_meals` INT NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `tipus_dieta` BIGINT(10) NULL,
  PRIMARY KEY (`id_diet`),
  CONSTRAINT `FK_TYPE_DIETS`
    FOREIGN KEY (`tipus_dieta`)
    REFERENCES `mydb`.`type_diets` (`id_type`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FK_TYPE_DIETS_idx` ON `mydb`.`diets` (`tipus_dieta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`nutricionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nutricionist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nutricionist` (
  `id_nutricionist` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_nutricionist`),
  CONSTRAINT `FK_USERS_ID`
    FOREIGN KEY (`id_nutricionist`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pacient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pacient` (
  `id_pacient` BIGINT(10) UNSIGNED NOT NULL,
  `assigned_nutricionist` BIGINT(10) UNSIGNED NULL,
  `email_pacient` VARCHAR(45) NULL,
  `phone_pacient` VARCHAR(20) NULL,
  `address_pacient` VARCHAR(1000) NULL,
  `current_diet` BIGINT(10) UNSIGNED NULL,
  PRIMARY KEY (`id_pacient`),
  CONSTRAINT `FK_PACIENT_DIETAS`
    FOREIGN KEY (`current_diet`)
    REFERENCES `mydb`.`diets` (`id_diet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PACIENT_USERS`
    FOREIGN KEY (`id_pacient`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PACIENT_NUTRICIONISTA`
    FOREIGN KEY (`assigned_nutricionist`)
    REFERENCES `mydb`.`nutricionist` (`id_nutricionist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_PACIENT_DIETAS_idx` ON `mydb`.`pacient` (`current_diet` ASC) VISIBLE;

CREATE INDEX `FK_PACIENT_NUTRICIONISTA_idx` ON `mydb`.`pacient` (`assigned_nutricionist` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`historial_pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historial_pacient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historial_pacient` (
  `id_historial` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `id_pacient` BIGINT(10) UNSIGNED NOT NULL,
  `diet` BIGINT(10) UNSIGNED NOT NULL,
  `weigth` DECIMAL(6,2) NOT NULL,
  `heigth` DECIMAL(6,2) NOT NULL,
  `chest` DECIMAL(6,2) NULL,
  `leg` DECIMAL(6,2) NULL,
  `arm` DECIMAL(6,2) NULL,
  `hip` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id_historial`, `date`),
  CONSTRAINT `FK_ID_PACIENT`
    FOREIGN KEY (`id_pacient`)
    REFERENCES `mydb`.`pacient` (`id_pacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISTORIAL_DIETA`
    FOREIGN KEY (`diet`)
    REFERENCES `mydb`.`diets` (`id_diet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_HISTORIAL_DIETA_idx` ON `mydb`.`historial_pacient` (`diet` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dishes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dishes` (
  `id_dishes` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_dishes` VARCHAR(100) NOT NULL,
  `calories` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_dishes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unit_mesure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`unit_mesure` ;

CREATE TABLE IF NOT EXISTS `mydb`.`unit_mesure` (
  `id_unit` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `abreviation` VARCHAR(45) NOT NULL,
  `unit_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_unit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
  `id_ingredient` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(10,2) NOT NULL,
  `calories_unit` BIGINT(10) UNSIGNED NULL,
  PRIMARY KEY (`id_ingredient`),
  CONSTRAINT `FK_INGREDIENTS_MESURE`
    FOREIGN KEY (`calories_unit`)
    REFERENCES `mydb`.`unit_mesure` (`id_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_INGREDIENTS_MESURE_idx` ON `mydb`.`ingredients` (`calories_unit` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`meal_dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`meal_dishes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`meal_dishes` (
  `id_meal` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_meal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_meal`, `name_meal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`week_days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`week_days` ;

CREATE TABLE IF NOT EXISTS `mydb`.`week_days` (
  `id_day` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_day`, `name_day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diets_dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`diets_dishes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`diets_dishes` (
  `dietas_id_dieta` BIGINT(10) UNSIGNED NULL,
  `dishes_id_dishes` BIGINT(10) UNSIGNED NOT NULL,
  `week_day` BIGINT(10) UNSIGNED NULL,
  `meal` BIGINT(10) UNSIGNED NULL,
  PRIMARY KEY (`dietas_id_dieta`, `dishes_id_dishes`, `week_day`, `meal`),
  CONSTRAINT `fk_Dietas_has_Dishes_Dietas1`
    FOREIGN KEY (`dietas_id_dieta`)
    REFERENCES `mydb`.`diets` (`id_diet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dietas_has_Dishes_Dishes1`
    FOREIGN KEY (`dishes_id_dishes`)
    REFERENCES `mydb`.`dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DIETSDISHES_MEAL`
    FOREIGN KEY (`meal`)
    REFERENCES `mydb`.`meal_dishes` (`id_meal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DIETDISHES_WEEKDAYS`
    FOREIGN KEY (`week_day`)
    REFERENCES `mydb`.`week_days` (`id_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Dietas_has_Dishes_Dishes1_idx` ON `mydb`.`diets_dishes` (`dishes_id_dishes` ASC) VISIBLE;

CREATE INDEX `fk_Dietas_has_Dishes_Dietas1_idx` ON `mydb`.`diets_dishes` (`dietas_id_dieta` ASC) VISIBLE;

CREATE INDEX `FK_DIETSDISHES_MEAL_idx` ON `mydb`.`diets_dishes` (`meal` ASC) VISIBLE;

CREATE INDEX `FK_DIETDISHES_WEEKDAYS_idx` ON `mydb`.`diets_dishes` (`week_day` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`dishes_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dishes_ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dishes_ingredients` (
  `dishes_id_dishes` BIGINT(10) UNSIGNED NOT NULL,
  `ingredients_id_ingredient` BIGINT(10) UNSIGNED NOT NULL,
  `quantity` DECIMAL(10,2) UNSIGNED NULL,
  `mesure` BIGINT(10) UNSIGNED NULL,
  PRIMARY KEY (`dishes_id_dishes`, `ingredients_id_ingredient`),
  CONSTRAINT `fk_Ingridients_has_Dishes_Ingridients1`
    FOREIGN KEY (`ingredients_id_ingredient`)
    REFERENCES `mydb`.`ingredients` (`id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingridients_has_Dishes_Dishes1`
    FOREIGN KEY (`dishes_id_dishes`)
    REFERENCES `mydb`.`dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dishes_Ingredients_Unit Mesure1`
    FOREIGN KEY (`mesure`)
    REFERENCES `mydb`.`unit_mesure` (`id_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ingridients_has_Dishes_Dishes1_idx` ON `mydb`.`dishes_ingredients` (`dishes_id_dishes` ASC) VISIBLE;

CREATE INDEX `fk_Ingridients_has_Dishes_Ingridients1_idx` ON `mydb`.`dishes_ingredients` (`ingredients_id_ingredient` ASC) VISIBLE;

CREATE INDEX `fk_Dishes_Ingredients_Unit Mesure1_idx` ON `mydb`.`dishes_ingredients` (`mesure` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
