-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 17:54:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id_user` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NOT NULL,
  `lastName_user` VARCHAR(45) NOT NULL,
  `nickname_user` VARCHAR(45) NOT NULL,
  `password_user` VARCHAR(45) NOT NULL,
  `type_user` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nutricionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nutricionist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nutricionist` (
  `id_nutricionist` BIGINT(10) NOT NULL,
  PRIMARY KEY (`id_nutricionist`),
  CONSTRAINT `FK_ID_NUTRICIONISTA`
    FOREIGN KEY (`id_nutricionist`)
    REFERENCES `mydb`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_ID_NUTRICIONISTA_idx` ON `mydb`.`Nutricionist` (`id_nutricionist` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Diets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Diets` (
  `id_dieta` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_dieta` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(2) NOT NULL,
  `number_meals` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dieta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pacient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pacient` (
  `id_pacient` BIGINT(10) NOT NULL,
  `assigned_nutricionist` BIGINT(10) NULL,
  `email_pacient` VARCHAR(45) NULL,
  `phone_pacient` VARCHAR(45) NULL,
  `address_pacient` VARCHAR(45) NULL,
  `current_diet` BIGINT(10) NULL,
  PRIMARY KEY (`id_pacient`),
  CONSTRAINT `FK_PACIENT_NUTRICIONISTA`
    FOREIGN KEY (`assigned_nutricionist`)
    REFERENCES `mydb`.`Nutricionist` (`id_nutricionist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PACIENT_DIETAS`
    FOREIGN KEY (`current_diet`)
    REFERENCES `mydb`.`Diets` (`id_dieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PACIENT_USERS`
    FOREIGN KEY (`id_pacient`)
    REFERENCES `mydb`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pacient_Nutricionista1_idx` ON `mydb`.`Pacient` (`assigned_nutricionist` ASC) VISIBLE;

CREATE INDEX `FK_PACIENT_DIETAS_idx` ON `mydb`.`Pacient` (`current_diet` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Historial_Pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Historial_Pacient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Historial_Pacient` (
  `id_historial` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pacient` BIGINT(10) NOT NULL,
  `date` DATE NOT NULL,
  `diet` BIGINT(10) NOT NULL,
  `weigth` DECIMAL(2) NULL,
  `heigth` DECIMAL(2) NULL,
  `imc` DECIMAL(2) NULL,
  `chest` DECIMAL(2) NULL,
  `leg` DECIMAL(2) NULL,
  `arm` DECIMAL(2) NULL,
  `hip` DECIMAL(2) NULL,
  PRIMARY KEY (`id_historial`, `date`),
  CONSTRAINT `FK_ID_PACIENT`
    FOREIGN KEY (`id_pacient`)
    REFERENCES `mydb`.`Pacient` (`id_pacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISTORIAL_DIETA`
    FOREIGN KEY (`diet`)
    REFERENCES `mydb`.`Diets` (`id_dieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_HISTORIAL_DIETA_idx` ON `mydb`.`Historial_Pacient` (`diet` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dishes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dishes` (
  `id_dishes` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_dishes` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_dishes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `id_ingridient` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ingridient_name` VARCHAR(45) NOT NULL,
  `ingridient_calories` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_ingridient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diets_has_Dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Diets_has_Dishes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Diets_has_Dishes` (
  `Dietas_id_dieta` BIGINT(10) NOT NULL,
  `Dishes_id_dishes` BIGINT(10) NOT NULL,
  `week_day` VARCHAR(45) NOT NULL,
  `meal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dietas_id_dieta`, `Dishes_id_dishes`),
  CONSTRAINT `fk_Dietas_has_Dishes_Dietas1`
    FOREIGN KEY (`Dietas_id_dieta`)
    REFERENCES `mydb`.`Diets` (`id_dieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dietas_has_Dishes_Dishes1`
    FOREIGN KEY (`Dishes_id_dishes`)
    REFERENCES `mydb`.`Dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Dietas_has_Dishes_Dishes1_idx` ON `mydb`.`Diets_has_Dishes` (`Dishes_id_dishes` ASC) VISIBLE;

CREATE INDEX `fk_Dietas_has_Dishes_Dietas1_idx` ON `mydb`.`Diets_has_Dishes` (`Dietas_id_dieta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Dishes_Has_ Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dishes_Has_ Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dishes_Has_ Ingredients` (
  `Ingredients_id_ingredient` BIGINT(10) NOT NULL,
  `Dishes_id_dishes` BIGINT(10) NOT NULL,
  `quantity` DECIMAL(2) NOT NULL,
  `unit_mesure` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ingredients_id_ingredient`, `Dishes_id_dishes`),
  CONSTRAINT `fk_Ingridients_has_Dishes_Ingridients1`
    FOREIGN KEY (`Ingredients_id_ingredient`)
    REFERENCES `mydb`.`Ingredients` (`id_ingridient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingridients_has_Dishes_Dishes1`
    FOREIGN KEY (`Dishes_id_dishes`)
    REFERENCES `mydb`.`Dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ingridients_has_Dishes_Dishes1_idx` ON `mydb`.`Dishes_Has_ Ingredients` (`Dishes_id_dishes` ASC) VISIBLE;

CREATE INDEX `fk_Ingridients_has_Dishes_Ingridients1_idx` ON `mydb`.`Dishes_Has_ Ingredients` (`Ingredients_id_ingredient` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
