-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 17:33:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projecte3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projecte3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projecte3` DEFAULT CHARACTER SET utf8 ;
USE `projecte3` ;

-- -----------------------------------------------------
-- Table `projecte3`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`users` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`users` (
  `id_user` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NOT NULL,
  `lastName_user` VARCHAR(45) NOT NULL,
  `nickname_user` VARCHAR(45) NOT NULL,
  `password_user` VARCHAR(45) NOT NULL,
  `type_user` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`diets` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`diets` (
  `id_dieta` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(2) NOT NULL,
  `number_meals` INT NOT NULL,
  `type` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_dieta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`nutricionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`nutricionist` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`nutricionist` (
  `id_nutricionist` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_nutricionist`),
  CONSTRAINT `FK_USERS_ID`
    FOREIGN KEY (`id_nutricionist`)
    REFERENCES `projecte3`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`pacient` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`pacient` (
  `id_pacient` BIGINT(10) UNSIGNED NOT NULL,
  `assigned_nutricionist` BIGINT(10) UNSIGNED NULL,
  `email_pacient` VARCHAR(45) NULL,
  `phone_pacient` VARCHAR(45) NULL,
  `address_pacient` VARCHAR(45) NULL,
  `current_diet` BIGINT(10) UNSIGNED NULL,
  PRIMARY KEY (`id_pacient`),
  INDEX `FK_PACIENT_DIETAS_idx` (`current_diet` ASC),
  INDEX `FK_PACIENT_NUTRICIONISTA_idx` (`assigned_nutricionist` ASC),
  CONSTRAINT `FK_PACIENT_DIETAS`
    FOREIGN KEY (`current_diet`)
    REFERENCES `projecte3`.`diets` (`id_dieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PACIENT_USERS`
    FOREIGN KEY (`id_pacient`)
    REFERENCES `projecte3`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PACIENT_NUTRICIONISTA`
    FOREIGN KEY (`assigned_nutricionist`)
    REFERENCES `projecte3`.`nutricionist` (`id_nutricionist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`historial_Pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`historial_Pacient` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`historial_Pacient` (
  `id_historial` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `id_pacient` BIGINT(10) UNSIGNED NOT NULL,
  `diet` BIGINT(10) UNSIGNED NOT NULL,
  `weigth` DECIMAL(2) NOT NULL,
  `heigth` DECIMAL(2) NOT NULL,
  `chest` DECIMAL(2) NULL,
  `leg` DECIMAL(2) NULL,
  `arm` DECIMAL(2) NULL,
  `hip` DECIMAL(2) NULL,
  PRIMARY KEY (`id_historial`, `date`),
  INDEX `FK_HISTORIAL_DIETA_idx` (`diet` ASC) ,
  CONSTRAINT `FK_ID_PACIENT`
    FOREIGN KEY (`id_pacient`)
    REFERENCES `projecte3`.`pacient` (`id_pacient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISTORIAL_DIETA`
    FOREIGN KEY (`diet`)
    REFERENCES `projecte3`.`diets` (`id_dieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`dishes` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`dishes` (
  `id_dishes` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_dishes` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_dishes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`ingredients` (
  `id_ingridient` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_ingridient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`diets_dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`diets_dishes` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`diets_dishes` (
  `dietas_id_dieta` BIGINT(10) UNSIGNED NOT NULL,
  `dishes_id_dishes` BIGINT(10) UNSIGNED NOT NULL,
  `week_day` VARCHAR(45) NOT NULL,
  `meal` VARCHAR(45) NOT NULL,
  INDEX `fk_Dietas_has_Dishes_Dishes1_idx` (`dishes_id_dishes` ASC) ,
  INDEX `fk_Dietas_has_Dishes_Dietas1_idx` (`dietas_id_dieta` ASC) ,
  PRIMARY KEY (`dietas_id_dieta`, `dishes_id_dishes`, `week_day`, `meal`),
  CONSTRAINT `fk_Dietas_has_Dishes_Dietas1`
    FOREIGN KEY (`dietas_id_dieta`)
    REFERENCES `projecte3`.`diets` (`id_dieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dietas_has_Dishes_Dishes1`
    FOREIGN KEY (`dishes_id_dishes`)
    REFERENCES `projecte3`.`dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`unit_mesure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`unit_mesure` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`unit_mesure` (
  `id_unit` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `unit_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_unit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecte3`.`dishes_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecte3`.`dishes_ingredients` ;

CREATE TABLE IF NOT EXISTS `projecte3`.`dishes_ingredients` (
  `Ingredients_id_ingredient` BIGINT(10) UNSIGNED NOT NULL,
  `dishes_id_dishes` BIGINT(10) UNSIGNED NOT NULL,
  `quantity` DECIMAL(2) NOT NULL,
  `mesure` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Ingredients_id_ingredient`, `dishes_id_dishes`),
  INDEX `fk_Ingridients_has_Dishes_Dishes1_idx` (`dishes_id_dishes` ASC) ,
  INDEX `fk_Ingridients_has_Dishes_Ingridients1_idx` (`Ingredients_id_ingredient` ASC) ,
  INDEX `fk_Dishes_Ingredients_Unit Mesure1_idx` (`mesure` ASC) ,
  CONSTRAINT `fk_Ingridients_has_Dishes_Ingridients1`
    FOREIGN KEY (`Ingredients_id_ingredient`)
    REFERENCES `projecte3`.`ingredients` (`id_ingridient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingridients_has_Dishes_Dishes1`
    FOREIGN KEY (`dishes_id_dishes`)
    REFERENCES `projecte3`.`dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dishes_Ingredients_Unit Mesure1`
    FOREIGN KEY (`mesure`)
    REFERENCES `projecte3`.`unit_mesure` (`id_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
